spring:
  application:
    name: eureka-server
server:
  port: ${PORT:8762}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl: 
     defaultZone: https://ms-eureka-server.herokuapp.com/eureka
