spring:
  application:
    name: eureka-server
server:
  port: ${PORT:8080}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl: 
     defaultZone: https://eureka-server-gcp.appspot.com/eureka